#!/usr/bin/env python3

import json
import random
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent

CONTENT_FILE = ROOT / "content" / "topics.json"
DAILY_ROOT = ROOT / "daily"
STATISTICS_ROOT = ROOT / "statistics"

TIMEZONE = ZoneInfo("Asia/Beirut")


def load_topics():
    with CONTENT_FILE.open("r", encoding="utf-8") as file:
        return json.load(file)


def get_existing_entries(day_directory):
    if not day_directory.exists():
        return []

    return list(day_directory.glob("*.md"))


def choose_topic(topics, existing_entries):
    used_names = {
        entry.stem.split("-", 1)[-1]
        for entry in existing_entries
    }

    unused_topics = [
        topic
        for topic in topics
        if topic["topic"]
        .lower()
        .replace(" ", "_")
        not in used_names
    ]

    if unused_topics:
        return random.choice(unused_topics)

    return random.choice(topics)


def slugify(value):
    return (
        value.lower()
        .replace(" ", "_")
        .replace("/", "_")
        .replace("-", "_")
    )


def update_statistics(date_string):
    STATISTICS_ROOT.mkdir(parents=True, exist_ok=True)

    stats_file = STATISTICS_ROOT / "daily.json"

    if stats_file.exists():
        with stats_file.open("r", encoding="utf-8") as file:
            stats = json.load(file)
    else:
        stats = {}

    stats.setdefault(date_string, 0)
    stats[date_string] += 1

    with stats_file.open("w", encoding="utf-8") as file:
        json.dump(stats, file, indent=2)


def main():
    now = datetime.now(TIMEZONE)

    year = now.strftime("%Y")
    month = now.strftime("%m")
    day = now.strftime("%d")
    date_string = now.strftime("%Y-%m-%d")
    time_string = now.strftime("%H:%M:%S")

    day_directory = DAILY_ROOT / year / month / day
    day_directory.mkdir(parents=True, exist_ok=True)

    topics = load_topics()

    existing_entries = get_existing_entries(day_directory)

    sequence = len(existing_entries) + 1

    topic = choose_topic(topics, existing_entries)

    slug = slugify(topic["topic"])

    filename = f"{sequence:02d}-{slug}.md"

    output_file = day_directory / filename

    markdown = f"""# {topic["topic"]}

**Date:** {date_string}

**Time:** {time_string} Asia/Beirut

**Category:** {topic["category"]}

## Today's Focus

{topic["focus"]}

## Practice

{topic["practice"]}

## Key Point

{topic["key_point"]}

## Engineering Log

Daily engineering knowledge entry generated by the contribution engine.

---

Entry: {sequence}
"""

    with output_file.open("w", encoding="utf-8") as file:
        file.write(markdown)

    update_statistics(date_string)

    print(f"Created: {output_file}")


if __name__ == "__main__":
    main()
